# Usar Windows con Python 3.9 x64
image: Visual Studio 2022

environment:
  matrix:
    - PYTHON: "C:\\Python39-x64"

install:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python -m pip install --upgrade pip
  - python -m pip install pyinstaller pandas matplotlib tk

build_script:
  - python -m PyInstaller --onefile --windowed NTGS-Tubos.py

artifacts:
  - path: dist\NTGS-Tubos.exe
    name: NTGS-Tubos
